name: CI

env:
  COMPOSE_INTERACTIVE_NO_CLI: 1
  PHP_CS_FIXER_IGNORE_ENV: 1
  LEAN_MYSQL_PORT: 3307
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  phpunit:
    name: Tests (PHPUnit) L${{ matrix.laravel }}
    strategy:
      matrix:
        laravel: [6, 8, 9]
        include:
        - laravel: 6
            testbench: ^4.0
        - laravel: 8
            testbench: ^6.0
          - laravel: 9.*
            testbench: ^7.0


    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install composer dependencies
      run: composer require "laravel/framework:^${{matrix.laravel}}.0" "orchestra/testbench:${{ matrix.testbench }}"
    - name: Run tests
      run: vendor/bin/phpunit

  phpstan:
    name: Static analysis (PHPStan)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install composer dependencies
      run: composer install
    - name: Run phpstan
      run: vendor/bin/phpstan analyse

  php-cs-fixer:
    name: Code style (php-cs-fixer)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install php-cs-fixer
        run: composer global require friendsofphp/php-cs-fixer
      - name: Run php-cs-fixer
        run: $HOME/.composer/vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php
      - name: Commit changes from php-cs-fixer
        uses: EndBug/add-and-commit@v5
        with:
          author_name: Samuel Štancl
          author_email: samuel.stancl@gmail.com
          message: Fix code style (php-cs-fixer)
